name: Roblox Playwright Automation

on:
  workflow_dispatch:

jobs:
  roblox:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:

      # -------------------------------------------------------
      # Descargar repositorio
      # -------------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4


      # -------------------------------------------------------
      # Node.js
      # -------------------------------------------------------

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm


      # -------------------------------------------------------
      # Dependencias
      # -------------------------------------------------------

      - name: Install npm dependencies
        run: npm ci
      - name: Instalar dependencias node
        run: |
          npm install

      # -------------------------------------------------------
      # Chromium
      # -------------------------------------------------------

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium


      # -------------------------------------------------------
      # Comprobar vídeos
      # -------------------------------------------------------

      - name: Check videos
        run: |
          echo "Comprobando vídeos..."

          test -f videos/video1.mp4
          test -f videos/video2.mp4
          test -f videos/video3.mp4

          echo "Video 1:"
          ls -lh videos/video1.mp4

          echo "Video 2:"
          ls -lh videos/video2.mp4

          echo "Video 3:"
          ls -lh videos/video3.mp4


      # -------------------------------------------------------
      # Ejecutar Playwright
      # -------------------------------------------------------

      - name: Run Roblox automation
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
        run: |
          node change-language.js


      # -------------------------------------------------------
      # Captura si falla
      # -------------------------------------------------------

      - name: Upload debug files
        if: failure()
        uses: actions/upload-artifact@v4

        with:
          name: roblox-debug

          path: |
            error-screenshot.png
            error-page.html

          if-no-files-found: ignore
