name: Cambiar idioma de Roblox

on:
  workflow_dispatch:

jobs:
  change-language:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v5

      - name: Verificar archivos
        run: |
          echo "Directorio actual:"
          pwd

          echo ""
          echo "Contenido:"
          ls -la

          echo ""
          echo "Buscando package-lock.json:"
          find . -name "package-lock.json" -print

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar Chromium
        run: npx playwright install --with-deps chromium

      - name: Cambiar idioma
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
        run: npm run run
